---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
resources:
- name: platform-automation
  type: pivnet
  source:
    product_slug: platform-automation
    api_token: ((pivnet-refresh-token))
- name: env
  type: git
  source:
    uri: git@github.com:bkirkware/kirklab-env
    private_key: ((platform-automation-pipelines-kirklab-deploy-key-readonly.private_key))
    branch: master
- name: installation
  type: s3
  source:
    access_key_id: ((s3.access_key_id))
    bucket: ((s3.buckets.installation))
    region_name: ((s3.region_name))
    secret_access_key: ((s3.secret_access_key))
    regexp: installation-(.*).zip
jobs:
- name: export-installation
  plan:
    - get: platform-automation-image
      resource: platform-automation
      params:
        globs: ["*image*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        globs: ["*tasks*.zip"]
        unpack: true
    - get: env
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      input_mapping:
        files: env
      params:
        # all required
        CREDHUB_CA_CERT: ((credhub_ca_cert))
        CREDHUB_CLIENT: ((credhub_client))
        CREDHUB_SECRET: ((credhub_secret))
        CREDHUB_SERVER: ((credhub_server))
        PREFIX: /kirklab
    - task: export-installation
      image: platform-automation-image
      file: platform-automation-tasks/tasks/export-installation.yml
      input_mapping:
        env: interpolated-files
    - put: installation
      params:
        file: installation/installation-*.zip