resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:

- name: platform-automation-pivnet
  type: pivnet
  source:
    api_token: ((pivnet-refresh-token))
    product_slug: platform-automation
    product_version: 2\.(.*)
    sort_by: semver

- name: platform-automation-tasks
  type: s3
  source:
    access_key_id: ((minio_access_key_id))
    secret_access_key: ((minio_secret_access_key))
    endpoint: ((minio_endpoint))
    bucket: ((minio_buckets_pivnet_products))
    regexp: platform-automation-tasks-(.*).zip
    disable_ssl: true

- name: platform-automation-image
  type: s3
  source:
    access_key_id: ((minio_access_key_id))
    secret_access_key: ((minio_secret_access_key))
    endpoint: ((minio_endpoint))
    bucket: ((minio_buckets_pivnet_products))
    regexp: platform-automation-image-(.*).tgz
    disable_ssl: true

jobs:

- name: fetch-platform-automation
  # We use the pivnet resource to bootstrap the pipeline,
  # and because this product is part of the pipeline, not the foundation
  plan:
  - get: platform-automation-pivnet
    trigger: true
  - aggregate:
    - put: platform-automation-tasks
      params:
        file: platform-automation-pivnet/*tasks*.zip
    - put: platform-automation-image
      params:
        file: platform-automation-pivnet/*image*.tgz